name: Tester

on:
  workflow_dispatch:
    inputs:
      env:
        description: env
        type: choice
        options:
          - preprod
          - prod
          
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cluster: ${{ steps.prepare.outputs.cluster }}
    steps:
      - name: Prepare Values
        id: prepare
        run: |
          if [[ "${{ inputs.env }}" == "prod" ]]; then
            echo "cluster=prod-cluster" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ inputs.env }}" == "preprod" ]]; then
            echo "cluster=preprod-cluster" >> $GITHUB_OUTPUT
          fi
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy working-directory
        run: echo "The cluster is ${{ needs.build.outputs.cluster }}"
    
